name: mnemosym
channels:
- defaults
- conda-forge
dependencies:
- python~=3.10
- discord.py~=1.7.3
- black~=22.1.0
- safety~=1.10.3
- bandit~=1.7.4
- pylint~=2.13.0
- pre-commit~=2.17.0
- python-dotenv~=0.20.0
- tqdm~=4.63.0